# Generated by Django 5.0 on 2024-02-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='code_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
