# Generated by Django 5.0 on 2024-02-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sales_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
